version: '3'
services:
  web:
    environment:
      - BACKEND_LOGIN_URL=https://svm-61.cs.helsinki.fi/labtool-backend/
      - PUBLIC_HOST=svm-61.cs.helsinki.fi
      - PUBLIC_PATH=/labtool
      - PUBLIC_URL=https://svm-61.cs.helsinki.fi/labtool/...
    image: labtool/labtool:test
    ports:
     - "6000:3000"
    depends_on:
     - backend
     - db
  backend:
    environment:
      - TOKEN=changeme
      - NODE_ENV=test
    image: labtool/labtool-backend:test
    ports:
      - "6001:3001"
    depends_on:
      - db
  db:
    environment:
      PGDATA: /data/pg10.1_labtool_2018k
    volumes:
      - /data/pg10.1_labtool_2018k:/data/pg10.1_labtool_2018k
    image: postgres:10.1
    restart: unless-stopped
