version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - db
  db:
    environment:
      PGDATA: /data/pg_db
      POSTGRES_PASSWORD: example
    volumes:
      - /data/pg_db:/data/pg_db
    image: postgres:10.1
    restart: unless-stopped
