PUT http://localhost:3001/api/comments/update
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYW9wZXR0YWphIiwiaWQiOjEwMDEwLCJpYXQiOjE1NzMyNTA2MTZ9.QGBl0lVS_olLgjrpsN-wFkGRzD6PFcsuSXRs4f5ylPo

{
  "comments":[
    {
      "id":4,
      "weekId":10001,
      "isRead":[10011]
    }, 
    {
      "id":5,
      "weekId":10001,
      "isRead":[10011]
    }  
  ]
}